// Package routebridge owns a bounded, authenticated loopback CONNECT bridge.
// Provider TLS remains end-to-end; neither engine terminates or inspects it.
package routebridge

import (
	"bufio"
	"context"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"io"
	"net"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

const headerLimit = 8192
const maxConnections = 16

var hostPattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$`)
var localCredentialPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{16,128}$`)

var errConfig = errors.New("Invalid route configuration")
var errClosed = errors.New("Route closed")
var errConnect = errors.New("Route connection failed")

type dialFunc func(context.Context, string) (net.Conn, error)

// Route owns one transport and its loopback listener. Share a WireGuard Route
// across leases of the same saved identity instead of making roaming peers.
type Route struct {
	listener net.Listener
	ctx      context.Context
	cancel   context.CancelFunc
	dial     dialFunc
	allowed  []string
	auth     string
	realm    string
	cleanup  func()
	mu       sync.Mutex
	closed   bool
	sockets  map[net.Conn]struct{}
	once     sync.Once
	workers  sync.WaitGroup
	slots    chan struct{}
}

func validHost(host string) bool {
	return len(host) <= 253 && host == strings.ToLower(host) && hostPattern.MatchString(host) && net.ParseIP(host) == nil
}

func parseHosts(input string) ([]string, error) {
	if len(input) > 4096 {
		return nil, errConfig
	}
	hosts := strings.Split(input, ",")
	if len(hosts) == 0 || len(hosts) > 64 {
		return nil, errConfig
	}
	for _, host := range hosts {
		if host != "*-abematv.akamaized.net" && host != "*.ttvnw.net" && host != "*.twitchcdn.net" && !validHost(host) {
			return nil, errConfig
		}
	}
	return hosts, nil
}

func (r *Route) permits(host string) bool {
	if !validHost(host) {
		return false
	}
	for _, allowed := range r.allowed {
		if host == allowed {
			return true
		}
		if allowed == "*-abematv.akamaized.net" && strings.HasSuffix(host, "-abematv.akamaized.net") {
			prefix := strings.TrimSuffix(host, "-abematv.akamaized.net")
			if prefix != "" && !strings.Contains(prefix, ".") {
				return true
			}
		}
		if (allowed == "*.ttvnw.net" || allowed == "*.twitchcdn.net") && strings.HasSuffix(host, allowed[1:]) {
			prefix := strings.TrimSuffix(host, allowed[1:])
			if prefix != "" {
				return true
			}
		}
	}
	return false
}

func newRoute(username, password, realm, allowedHosts string, dial dialFunc, cleanup func()) (*Route, error) {
	hosts, err := parseHosts(allowedHosts)
	if err != nil || !localCredentialPattern.MatchString(username) || !localCredentialPattern.MatchString(password) || !localCredentialPattern.MatchString(realm) {
		return nil, errConfig
	}
	listener, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		return nil, errConnect
	}
	ctx, cancel := context.WithCancel(context.Background())
	r := &Route{listener: listener, ctx: ctx, cancel: cancel, dial: dial, allowed: hosts,
		auth: "Basic " + base64.StdEncoding.EncodeToString([]byte(username+":"+password)), realm: realm,
		cleanup: cleanup, sockets: make(map[net.Conn]struct{}), slots: make(chan struct{}, maxConnections)}
	r.workers.Add(1)
	go r.accept()
	return r, nil
}

// Port is the ephemeral loopback port. It contains no remote credentials.
func (r *Route) Port() int { return r.listener.Addr().(*net.TCPAddr).Port }

// GetPort provides the ordinary Java getter/Kotlin property generated by
// gomobile, while Port remains available to native fixture tests.
func (r *Route) GetPort() int { return r.Port() }

// Close cancels pending dials and active connections, then releases the engine.
func (r *Route) Close() error {
	r.once.Do(func() {
		r.cancel()
		r.listener.Close()
		r.mu.Lock()
		r.closed = true
		for socket := range r.sockets {
			socket.Close()
		}
		r.mu.Unlock()
		if r.cleanup != nil {
			r.cleanup()
		}
		r.workers.Wait()
	})
	return nil
}

func (r *Route) track(socket net.Conn) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.closed {
		socket.Close()
		return false
	}
	r.sockets[socket] = struct{}{}
	return true
}

func (r *Route) untrack(socket net.Conn) {
	socket.Close()
	r.mu.Lock()
	delete(r.sockets, socket)
	r.mu.Unlock()
}

func (r *Route) accept() {
	defer r.workers.Done()
	for {
		socket, err := r.listener.Accept()
		if err != nil {
			return
		}
		select {
		case r.slots <- struct{}{}:
		default:
			socket.Close()
			continue
		}
		if !r.track(socket) {
			<-r.slots
			continue
		}
		r.workers.Add(1)
		go func() { defer r.workers.Done(); defer func() { <-r.slots }(); defer r.untrack(socket); r.serve(socket) }()
	}
}

// readHeaders never consumes tunneled bytes: the same buffered reader is used
// for the copy after CONNECT, including bytes arriving in the same TCP packet.
func readHeaders(reader *bufio.Reader) (*http.Request, error) {
	var text strings.Builder
	for text.Len() <= headerLimit {
		bytes, err := reader.ReadSlice('\n')
		line := string(bytes)
		if err != nil || len(line)+text.Len() > headerLimit || !strings.HasSuffix(line, "\r\n") {
			return nil, errConnect
		}
		text.WriteString(line)
		if line == "\r\n" {
			return http.ReadRequest(bufio.NewReader(strings.NewReader(text.String())))
		}
	}
	return nil, errConnect
}

func (r *Route) serve(client net.Conn) {
	client.SetDeadline(time.Now().Add(15 * time.Second))
	reader := bufio.NewReaderSize(client, headerLimit+1)
	request, err := readHeaders(reader)
	if err != nil {
		return
	}
	if request.Method != "CONNECT" || request.Proto != "HTTP/1.1" || request.ContentLength > 0 || len(request.TransferEncoding) != 0 || request.URL.User != nil {
		io.WriteString(client, "HTTP/1.1 400 Bad Request\r\nConnection: close\r\nContent-Length: 0\r\n\r\n")
		return
	}
	provided := request.Header.Values("Proxy-Authorization")
	if len(provided) != 1 || subtle.ConstantTimeCompare([]byte(provided[0]), []byte(r.auth)) != 1 {
		io.WriteString(client, "HTTP/1.1 407 Proxy Authentication Required\r\nProxy-Authenticate: Basic realm=\""+r.realm+"\"\r\nConnection: close\r\nContent-Length: 0\r\n\r\n")
		return
	}
	host, port, err := net.SplitHostPort(request.Host)
	if err != nil || port != "443" || request.URL.Host != request.Host || !r.permits(host) {
		io.WriteString(client, "HTTP/1.1 403 Forbidden\r\nConnection: close\r\nContent-Length: 0\r\n\r\n")
		return
	}
	ctx, cancel := context.WithTimeout(r.ctx, 30*time.Second)
	defer cancel()
	upstream, err := r.dial(ctx, net.JoinHostPort(host, port))
	if err != nil {
		io.WriteString(client, "HTTP/1.1 502 Bad Gateway\r\nConnection: close\r\nContent-Length: 0\r\n\r\n")
		return
	}
	if !r.track(upstream) {
		return
	}
	defer r.untrack(upstream)
	if _, err := io.WriteString(client, "HTTP/1.1 200 Connection Established\r\n\r\n"); err != nil {
		return
	}
	// Bound idle/abandoned sockets independently from the presentation lifecycle.
	client.SetDeadline(time.Now().Add(5 * time.Minute))
	upstream.SetDeadline(time.Now().Add(5 * time.Minute))
	done := make(chan struct{})
	go func() { io.Copy(upstream, reader); upstream.Close(); client.Close(); close(done) }()
	io.Copy(client, upstream)
	upstream.Close()
	client.Close()
	<-done
}

// NewHttpProxy opens an authenticated local bridge to one remote HTTP CONNECT
// proxy. URI user-info is sent only to the proxy, never the tunneled origin.
func NewHttpProxy(config, username, password, realm, allowedHosts string) (*Route, error) {
	if len(config) > headerLimit {
		return nil, errConfig
	}
	proxy, err := url.Parse(config)
	if err != nil || proxy.Scheme != "http" || proxy.Hostname() == "" || proxy.RawQuery != "" || proxy.Fragment != "" || (proxy.Path != "" && proxy.Path != "/") {
		return nil, errConfig
	}
	port, err := strconv.Atoi(proxy.Port())
	if err != nil || port < 1 || port > 65535 {
		return nil, errConfig
	}
	remoteAuth := ""
	if proxy.User != nil {
		secret, ok := proxy.User.Password()
		user := proxy.User.Username()
		if !ok || user == "" || strings.ContainsAny(user+secret, "\r\n\x00") || strings.Contains(user, ":") {
			return nil, errConfig
		}
		remoteAuth = "Basic " + base64.StdEncoding.EncodeToString([]byte(user+":"+secret))
	}
	endpoint := net.JoinHostPort(proxy.Hostname(), proxy.Port())
	return newRoute(username, password, realm, allowedHosts, func(ctx context.Context, target string) (net.Conn, error) {
		connection, err := (&net.Dialer{}).DialContext(ctx, "tcp", endpoint)
		if err != nil {
			return nil, errConnect
		}
		stop := context.AfterFunc(ctx, func() { connection.Close() })
		ok := false
		defer func() {
			stop()
			if !ok {
				connection.Close()
			}
		}()
		if deadline, exists := ctx.Deadline(); exists {
			connection.SetDeadline(deadline)
		}
		header := "CONNECT " + target + " HTTP/1.1\r\nHost: " + target + "\r\n"
		if remoteAuth != "" {
			header += "Proxy-Authorization: " + remoteAuth + "\r\n"
		}
		if _, err := io.WriteString(connection, header+"\r\n"); err != nil {
			return nil, errConnect
		}
		reader := bufio.NewReaderSize(connection, headerLimit+1)
		response, err := readResponse(reader)
		if err != nil || response.StatusCode != 200 || response.ContentLength > 0 || len(response.TransferEncoding) != 0 {
			return nil, errConnect
		}
		connection.SetDeadline(time.Time{})
		ok = true
		return &bufferedConn{Conn: connection, reader: reader}, nil
	}, nil)
}

type bufferedConn struct {
	net.Conn
	reader *bufio.Reader
}

func (c *bufferedConn) Read(p []byte) (int, error) { return c.reader.Read(p) }

func readResponse(reader *bufio.Reader) (*http.Response, error) {
	var text strings.Builder
	for text.Len() <= headerLimit {
		bytes, err := reader.ReadSlice('\n')
		line := string(bytes)
		if err != nil || len(line)+text.Len() > headerLimit || !strings.HasSuffix(line, "\r\n") {
			return nil, errConnect
		}
		text.WriteString(line)
		if line == "\r\n" {
			return http.ReadResponse(bufio.NewReader(strings.NewReader(text.String())), &http.Request{Method: "CONNECT"})
		}
	}
	return nil, errConnect
}
